config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/reddit', as: 'reddit_login'

  get '/auth/reddit/callback',   to: 'sessions#create'
  get '/subreddits', to: 'subreddit#index', as: "my_subreddit"
  get '/:id/subreddit', to: 'subreddit#show',  as: "subreddit_show"

  resources :dashboard, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subreddit.rb
class Subreddit < ApplicationRecord
  belongs_to :user
  validates :dn, uniqueness: true

  def initialize(display_name, url, subscribers)
    @dn = display_name
    @url = url
    @subscribers = subscribers
  end


  def self.all(token)
    serv = RedditService.new(token)
    serv.subreddits.map do |subreddit|
      Subreddit.create(dn: subreddit[:data][:display_name],
                       url: subreddit[:data][:url],
                       subscribers: subreddit[:data][:subscribers])
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :subreddits
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid              = auth_info.uid
      new_user.username         = auth_info.info.name
      new_user.token            = auth_info.credentials.token
      new_user.token_expiration = auth_info.credentials.expires_at
      new_user.link_karma       = auth_info.extra.raw_info.link_karma
      new_user.comment_karma    = auth_info.extra.raw_info.comment_karma
    end
  end

  def expired?
    Time.now.to_i > token_expiration ? false : true
  end

  def subreddits(token)
    Subreddit.all(token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize!
    unless current_user
      redirect_to root_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authorize!
  def index
    if current_user
      @services = RedditService.new(current_user.token)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_info = request.env['omniauth.auth']

    if user = User.from_omniauth(auth_info)
      session[:user_id] = user.id
      current_user
    end

    redirect_to dashboard_index_path
  end
end

app/controllers/subreddit_controller.rb
class SubredditController < ApplicationController
  def index
    @service = RedditService.new(current_user.token)
  end
  def show
    service = RedditService.new(current_user.token)
    find_with(service)
  end

  private
    def find_with(service)
      service.subreddits.each do |sub|
        if sub[:data][:id] == params[:id]
          @subreddit = sub
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
  ID:  <%= current_user.id %> <br>
  UID:  <%= current_user.uid %> <br>
  Username:  <%= current_user.username %> <br>
  Token:  <%= current_user.token %> <br>
  Expiration: <%= Time.at(current_user.token_expiration) %> <br>
  Link Karma: <%= current_user.link_karma %> <br>
  Comment Karma: <%= current_user.comment_karma %> <br>
<%#= link_to "My Subreddits", "https://www.reddit.com/subreddits/mine/subscriber" %> <br>

<h3> <%= link_to "Subreddits", my_subreddit_path %> </h3>

app/views/home/index.html.erb
<%= link_to "Login with Reddit", reddit_login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiCuriousReddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subreddit/index.html.erb
<h2>Your Subreddits</h2>
<% @service.subreddits.each do |subreddit| %>
  <h4><%= link_to subreddit[:data][:display_name].capitalize, subreddit_show_path(subreddit[:data][:id]) %></h4>
  <%= subreddit[:data][:subscribers]%> subscribers <br>
  <%= subreddit[:data][:title].capitalize %></a> <br> <br>
<% end %>

app/views/subreddit/show.html.erb
<h2>Your Subreddits</h2>

  <h4><%= link_to @subreddit[:data][:display_name].capitalize, @subreddit_show_path %>:</h4> <%= @subreddit[:data][:subscribers]%> subscribers <br>
  <%= @subreddit[:data][:title].capitalize %></a> <br> <br>